### ISSUE TITLE
Cards stay open

### ISSUE THREAD

**Issue by pixelfabs** [mis-coder/memory-game#1]
Hi There!

Cards stay open in Chrome, even when they don't match. 

Chrome Version 90.0.4430.212 (Official Build) (64-bit) on Windows 7.

**Comment by mis-coder** [comment]
> Hi There!
> 
> Cards stay open in Chrome, even when they don't match.
> 
> Chrome Version 90.0.4430.212 (Official Build) (64-bit) on Windows 7.

Try agan!

**Comment by pixelfabs** [comment]
Yes! It's working! Thank you :-)
Sorry for my utterly late reply :(
